Repository Henryesc/Capstone, pull requests merged in 2023-07, with the labels that each got.

#9 add sectioning and view folder
  Capstone/sectioning/About-us.jsx
  Capstone/sectioning/Contact.jsx
  Capstone/sectioning/Gift-cards.jsx
  Capstone/sectioning/Landing.jsx
  Capstone/sectioning/Menu.jsx
  Capstone/sectioning/Order-pay.jsx
  Capstone/sectioning/index.js
  Capstone/view/Footer.jsx
  Capstone/view/Header.jsx
  Capstone/view/Main.jsx
  Capstone/view/index.js
Labels: 2, config

#18 017/hero section
  Capstone/assets/fonts/Caviar-Dreams/CaviarDreams.ttf
  Capstone/assets/fonts/Caviar-Dreams/CaviarDreams_BoldItalic.ttf
  Capstone/assets/fonts/Caviar-Dreams/CaviarDreams_Italic.ttf
  Capstone/assets/fonts/Caviar-Dreams/Caviar_Dreams_Bold.ttf
  Capstone/assets/fonts/Caviar-Dreams/Nymphont License.txt
  Capstone/assets/fonts/Josefin_Sans/JosefinSans-Italic-VariableFont_wght.ttf
  Capstone/assets/fonts/Josefin_Sans/JosefinSans-VariableFont_wght.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-Bold.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-BoldItalic.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-ExtraLight.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-ExtraLightItalic.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-Italic.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-Light.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-LightItalic.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-Medium.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-MediumItalic.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-Regular.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-SemiBold.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-SemiBoldItalic.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-Thin.ttf
  Capstone/assets/fonts/Josefin_Sans/static/JosefinSans-ThinItalic.ttf
  Capstone/assets/fonts/METROPOLIS 1920/Metropolis 1920.otf
  Capstone/assets/fonts/open-sans-condensed/Apache License.txt
  Capstone/assets/fonts/open-sans-condensed/OpenSans-CondBold.ttf
  Capstone/assets/fonts/open-sans-condensed/OpenSans-CondLight.ttf
  Capstone/assets/fonts/open-sans-condensed/OpenSans-CondLightItalic.ttf
  Capstone/assets/gvc.png
  Capstone/assets/restaurant.jpeg
  Capstone/components/hero-section/Background.jsx
  Capstone/components/index.js
  Capstone/sectioning/Header.jsx
  Capstone/sectioning/Main.jsx
  Capstone/src/App.css
  Capstone/view/Landing.jsx
Labels: 4, feature

#22 019/about us
  Capstone/assets/about-images/food-1.png
  Capstone/assets/bg-about-us.png
  Capstone/assets/vectors/vector-title.svg
  Capstone/components/about-us/About-us.jsx
  Capstone/components/about-us/Cards.jsx
  Capstone/components/index.js
  Capstone/components/title/Title.jsx
  Capstone/view/Landing.jsx
Labels: 4, feature

#28 add menu section component
  Capstone/assets/our-menu/bg-special-event.jpeg
  Capstone/assets/our-menu/dishpic.png
  Capstone/assets/vectors/burger-two.svg
  Capstone/components/index.js
  Capstone/components/our-menu/Menu-price.jsx
  Capstone/components/our-menu/Our-menu.jsx
  Capstone/view/Landing.jsx
Labels: 4, feature

#25 Add-testimonial-and-catering-code
  Capstone/app/store.js
  Capstone/assets/backgroundCateringSection.png
  Capstone/assets/blacklogo.png
  Capstone/assets/closequote.png
  Capstone/assets/linedeco.png
  Capstone/assets/openquote.png
  Capstone/assets/testimonials/betty-secondplate.png
  Capstone/assets/testimonials/christina-foodie.png
  Capstone/assets/testimonials/jimmy-buffet.png
  Capstone/assets/testimonials/patti-pickyeater.png
  Capstone/assets/testimonials/sally-smalltummy.png
  Capstone/assets/testimonials/samantha-hungryformore.png
  Capstone/assets/testimonials/shane-largetummy.png
  Capstone/components/CateringRequest.jsx
  Capstone/components/Testimonials.jsx
  Capstone/navs/testimonialsData.json
  Capstone/sectioning/Main.jsx
  Capstone/sectioning/index.js
  Capstone/src/App.css
  Capstone/src/App.jsx
  Capstone/src/main.jsx
  Capstone/view/Landing.jsx
  Capstone/view/index.js
Labels: feature

#52 049/database reviews
  package-lock.json
  package.json
  server.js
Labels: 4, config

#56 055/nav logo
  Capstone/sectioning/Header.jsx
Labels: 1

#58 fix hero section mobile
  Capstone/components/hero-section/Background.jsx
Labels: 1
